# Generated by Django 5.2.4 on 2025-07-25 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='adress',
            field=models.CharField(default='', max_length=100, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='storage',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Условие'),
        ),
        migrations.AddField(
            model_name='storageuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Локация'),
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(unique=True, verbose_name='Номер бокса')),
                ('area', models.IntegerField(verbose_name='Площадь')),
                ('length', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Длина')),
                ('width', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ширина')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Высота')),
                ('floor', models.IntegerField(default=0, verbose_name='Этаж')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='storageapp.storage', verbose_name='Склады')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_boxes', to=settings.AUTH_USER_MODEL, verbose_name='Клиенты')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('В процессе', 'В процессе'), ('Завершен', 'Завершен'), ('Отменен', 'Отменен'), ('Доставка', 'Доставка')], default='В процессе', max_length=100, verbose_name='Статус')),
                ('rental_start_date', models.DateTimeField(verbose_name='Дата начала заказа')),
                ('end_rental_date', models.DateField(verbose_name='Дата окончания заказа')),
                ('self_delivery', models.BooleanField(default=False)),
                ('storage_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиенты')),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField(verbose_name='Площадь')),
                ('length', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Длина')),
                ('width', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ширина')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Высота')),
                ('boxes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='box_items', to='storageapp.box', verbose_name='Вещи ячейки')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_items', to=settings.AUTH_USER_MODEL, verbose_name='Вещи Клиента')),
            ],
        ),
    ]
