# Generated by Django 5.2.4 on 2025-07-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0002_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritem',
            name='items',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание вещей'),
        ),
    ]
