# Generated by Django 5.2.4 on 2025-07-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0002_storage_adress_storage_condition_storageuser_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='temperature',
            field=models.IntegerField(default=1, verbose_name='Температура'),
        ),
    ]
