# Generated by Django 5.2.4 on 2025-07-25 13:16

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0003_alter_storage_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='user',
        ),
        migrations.AlterField(
            model_name='storageuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Номер телефона клиента', max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
