# Generated by Django 5.2.4 on 2025-07-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0003_alter_storage_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storage_images/', verbose_name='Изображение склада'),
        ),
    ]
