# Generated by Django 5.2.4 on 2025-07-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0003_alter_useritem_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='self_delivery',
            new_name='delivery',
        ),
    ]
