# Generated by Django 5.2.4 on 2025-07-28 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0004_rename_self_delivery_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritem',
            name='boxes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_items', to='storageapp.box', verbose_name='Вещи ячейки'),
        ),
    ]
