# Generated by Django 5.2.4 on 2025-07-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0004_rename_self_delivery_order_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('1_month', 'За 1 месяц'), ('2_weeks', 'За 2 недели'), ('1_week', 'За 1 неделю'), ('3_days', 'За 3 дня'), ('expired', 'Просрочка')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storageapp.order')),
            ],
            options={
                'unique_together': {('order', 'notification_type')},
            },
        ),
    ]
