# Generated by Django 5.2.4 on 2025-07-25 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0004_storage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='storageapp.box', verbose_name='Арендованный бокс'),
        ),
    ]
