# Generated by Django 5.2.4 on 2025-07-25 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0004_remove_storage_user_alter_storageuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_boxes', to=settings.AUTH_USER_MODEL, verbose_name='Клиенты'),
        ),
    ]
