# Generated by Django 5.2.4 on 2025-07-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0005_alter_box_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='condition',
        ),
        migrations.AlterField(
            model_name='storage',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Город'),
        ),
    ]
