# Generated by Django 5.2.4 on 2025-07-28 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0005_sentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='price_with_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена cо скидкой'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code_availability',
            field=models.BooleanField(default=False, verbose_name='наличие промокода'),
        ),
        migrations.AddField(
            model_name='order',
            name='rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена аренды'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='доставка'),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='boxes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_items', to='storageapp.box', verbose_name='Вещи ячейки'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(verbose_name='промокод')),
                ('discount_percent', models.IntegerField(verbose_name='процент скидки')),
                ('discount_start_date', models.DateField(verbose_name='дата начала скидки')),
                ('discount_end_date', models.DateField(verbose_name='дата конца скидки')),
                ('orders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='storageapp.order', verbose_name='Заказ со скидкой')),
            ],
        ),
    ]
