# Generated by Django 5.2.4 on 2025-07-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0005_alter_useritem_boxes'),
        ('storageapp', '0005_sentnotification'),
    ]

    operations = [
    ]
