# Generated by Django 5.2.4 on 2025-07-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0006_box_price_with_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='orders',
        ),
    ]
