# Generated by Django 5.2.4 on 2025-07-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0006_remove_storage_condition_alter_storage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storage_images/', verbose_name='Изображение склада'),
        ),
        migrations.AlterField(
            model_name='storageuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='storage_images/', verbose_name='Фото'),
        ),
    ]
