# Generated by Django 5.2.4 on 2025-07-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0007_remove_discount_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='orders', to='storageapp.discount', verbose_name='Промокоды'),
        ),
    ]
